version: '3.8'
services:
  nestjs-postgres:
    image: postgres:13
    container_name: nestjs-postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: pheng
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest-api-tuto
    networks:
      - nest-tuto
  
  test-db:
    image: postgres:13
    container_name: test-db
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: pheng
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test-db
    networks:
      - nest-tuto
networks:
  nest-tuto: